//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Costa.CostaSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", ConfigurationName="CostaSoap.ExportSoap")]
    public interface ExportSoap {
        
        // CODEGEN: Generating message contract since message ExportDestinationRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportDestination", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportDestinationResponse ExportDestination(Costa.CostaSoap.ExportDestinationRequest request);
        
        // CODEGEN: Generating message contract since message ExportPriceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportPriceResponse ExportPrice(Costa.CostaSoap.ExportPriceRequest request);
        
        // CODEGEN: Generating message contract since message ExportPriceWithPaxBreakdownRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportPriceWithPaxBreakdown", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportPriceWithPaxBreakdownResponse ExportPriceWithPaxBreakdown(Costa.CostaSoap.ExportPriceWithPaxBreakdownRequest request);
        
        // CODEGEN: Generating message contract since message ExportPriceDetailedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportPriceDetailed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportPriceDetailedResponse ExportPriceDetailed(Costa.CostaSoap.ExportPriceDetailedRequest request);
        
        // CODEGEN: Generating message contract since message ExportGroupPriceWithPaxBreakdownRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportGroupPriceWithPaxBreakdown", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportGroupPriceWithPaxBreakdownResponse ExportGroupPriceWithPaxBreakdown(Costa.CostaSoap.ExportGroupPriceWithPaxBreakdownRequest request);
        
        // CODEGEN: Generating message contract since message ExportTravelAgentPriceWithPaxBreakdownRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportTravelAgentPriceWithPaxBrea" +
            "kdown", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportTravelAgentPriceWithPaxBreakdownResponse ExportTravelAgentPriceWithPaxBreakdown(Costa.CostaSoap.ExportTravelAgentPriceWithPaxBreakdownRequest request);
        
        // CODEGEN: Generating message contract since message ExportPriceWithDestinationRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportPriceWithDestination", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportPriceWithDestinationResponse ExportPriceWithDestination(Costa.CostaSoap.ExportPriceWithDestinationRequest request);
        
        // CODEGEN: Generating message contract since message ExportCatalogRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportCatalog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportCatalogResponse ExportCatalog(Costa.CostaSoap.ExportCatalogRequest request);
        
        // CODEGEN: Generating message contract since message ExportRouletteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportRoulette", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportRouletteResponse ExportRoulette(Costa.CostaSoap.ExportRouletteRequest request);
        
        // CODEGEN: Generating message contract since message ExportAvailabilityRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportAvailability", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportAvailabilityResponse ExportAvailability(Costa.CostaSoap.ExportAvailabilityRequest request);
        
        // CODEGEN: Generating message contract since message ExportFareRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportFare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportFareResponse ExportFare(Costa.CostaSoap.ExportFareRequest request);
        
        // CODEGEN: Generating message contract since message ExportShipsAndCategoriesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportShipsAndCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportShipsAndCategoriesResponse ExportShipsAndCategories(Costa.CostaSoap.ExportShipsAndCategoriesRequest request);
        
        // CODEGEN: Generating message contract since message ExportPortsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportPorts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportPortsResponse ExportPorts(Costa.CostaSoap.ExportPortsRequest request);
        
        // CODEGEN: Generating message contract since message ExportItineraryAndStepsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportItineraryAndSteps", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportItineraryAndStepsResponse ExportItineraryAndSteps(Costa.CostaSoap.ExportItineraryAndStepsRequest request);
        
        // CODEGEN: Generating message contract since message ExportExcursionsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.costacrociere.com/WebAffiliation/ExportExcursions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Costa.CostaSoap.ExportExcursionsResponse ExportExcursions(Costa.CostaSoap.ExportExcursionsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
    public partial class Agency : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string cultureField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
    public partial class Partner : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportDestination", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportDestinationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        public ExportDestinationRequest() {
        }
        
        public ExportDestinationRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportDestinationResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportDestinationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportDestinationResult;
        
        public ExportDestinationResponse() {
        }
        
        public ExportDestinationResponse(string ExportDestinationResult) {
            this.ExportDestinationResult = ExportDestinationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPrice", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPriceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        public ExportPriceRequest() {
        }
        
        public ExportPriceRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            this.Agency = Agency;
            this.Partner = Partner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPriceResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportPriceResult;
        
        public ExportPriceResponse() {
        }
        
        public ExportPriceResponse(string ExportPriceResult) {
            this.ExportPriceResult = ExportPriceResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
    public enum ExportPriceType {
        
        /// <remarks/>
        Individual,
        
        /// <remarks/>
        HoneyMoon,
        
        /// <remarks/>
        Roulette,
        
        /// <remarks/>
        Bst,
        
        /// <remarks/>
        Value,
        
        /// <remarks/>
        PInd,
        
        /// <remarks/>
        Light,
        
        /// <remarks/>
        Valueai,
        
        /// <remarks/>
        Costa,
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Carrefou,
        
        /// <remarks/>
        Leclerc,
        
        /// <remarks/>
        Selecta,
        
        /// <remarks/>
        Spechvs,
        
        /// <remarks/>
        Promo,
        
        /// <remarks/>
        Valuebev,
        
        /// <remarks/>
        CWelcome,
        
        /// <remarks/>
        Welcome,
        
        /// <remarks/>
        CGeo,
        
        /// <remarks/>
        Geo,
        
        /// <remarks/>
        Colectiv,
        
        /// <remarks/>
        ECosta,
        
        /// <remarks/>
        EBasic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
    public enum MaxOccupancy {
        
        /// <remarks/>
        TwoPax,
        
        /// <remarks/>
        ThreePax,
        
        /// <remarks/>
        FourPax,
        
        /// <remarks/>
        FivePax,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPriceWithPaxBreakdown", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPriceWithPaxBreakdownRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=1)]
        public Costa.CostaSoap.ExportPriceType expPriceType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=2)]
        public Costa.CostaSoap.MaxOccupancy maxOccupancy;
        
        public ExportPriceWithPaxBreakdownRequest() {
        }
        
        public ExportPriceWithPaxBreakdownRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.ExportPriceType expPriceType, Costa.CostaSoap.MaxOccupancy maxOccupancy) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
            this.expPriceType = expPriceType;
            this.maxOccupancy = maxOccupancy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPriceWithPaxBreakdownResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPriceWithPaxBreakdownResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportPriceWithPaxBreakdownResult;
        
        public ExportPriceWithPaxBreakdownResponse() {
        }
        
        public ExportPriceWithPaxBreakdownResponse(string ExportPriceWithPaxBreakdownResult) {
            this.ExportPriceWithPaxBreakdownResult = ExportPriceWithPaxBreakdownResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPriceDetailed", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPriceDetailedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=1)]
        public Costa.CostaSoap.ExportPriceType expPriceType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=2)]
        public Costa.CostaSoap.MaxOccupancy maxOccupancy;
        
        public ExportPriceDetailedRequest() {
        }
        
        public ExportPriceDetailedRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.ExportPriceType expPriceType, Costa.CostaSoap.MaxOccupancy maxOccupancy) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
            this.expPriceType = expPriceType;
            this.maxOccupancy = maxOccupancy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPriceDetailedResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPriceDetailedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportPriceDetailedResult;
        
        public ExportPriceDetailedResponse() {
        }
        
        public ExportPriceDetailedResponse(string ExportPriceDetailedResult) {
            this.ExportPriceDetailedResult = ExportPriceDetailedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportGroupPriceWithPaxBreakdown", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportGroupPriceWithPaxBreakdownRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=1)]
        public Costa.CostaSoap.MaxOccupancy maxOccupancy;
        
        public ExportGroupPriceWithPaxBreakdownRequest() {
        }
        
        public ExportGroupPriceWithPaxBreakdownRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.MaxOccupancy maxOccupancy) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
            this.maxOccupancy = maxOccupancy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportGroupPriceWithPaxBreakdownResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportGroupPriceWithPaxBreakdownResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportGroupPriceWithPaxBreakdownResult;
        
        public ExportGroupPriceWithPaxBreakdownResponse() {
        }
        
        public ExportGroupPriceWithPaxBreakdownResponse(string ExportGroupPriceWithPaxBreakdownResult) {
            this.ExportGroupPriceWithPaxBreakdownResult = ExportGroupPriceWithPaxBreakdownResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportTravelAgentPriceWithPaxBreakdown", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportTravelAgentPriceWithPaxBreakdownRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=1)]
        public Costa.CostaSoap.MaxOccupancy maxOccupancy;
        
        public ExportTravelAgentPriceWithPaxBreakdownRequest() {
        }
        
        public ExportTravelAgentPriceWithPaxBreakdownRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.MaxOccupancy maxOccupancy) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
            this.maxOccupancy = maxOccupancy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportTravelAgentPriceWithPaxBreakdownResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportTravelAgentPriceWithPaxBreakdownResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportTravelAgentPriceWithPaxBreakdownResult;
        
        public ExportTravelAgentPriceWithPaxBreakdownResponse() {
        }
        
        public ExportTravelAgentPriceWithPaxBreakdownResponse(string ExportTravelAgentPriceWithPaxBreakdownResult) {
            this.ExportTravelAgentPriceWithPaxBreakdownResult = ExportTravelAgentPriceWithPaxBreakdownResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPriceWithDestination", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPriceWithDestinationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=1)]
        public Costa.CostaSoap.ExportPriceType expPriceType;
        
        public ExportPriceWithDestinationRequest() {
        }
        
        public ExportPriceWithDestinationRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.ExportPriceType expPriceType) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
            this.expPriceType = expPriceType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPriceWithDestinationResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPriceWithDestinationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportPriceWithDestinationResult;
        
        public ExportPriceWithDestinationResponse() {
        }
        
        public ExportPriceWithDestinationResponse(string ExportPriceWithDestinationResult) {
            this.ExportPriceWithDestinationResult = ExportPriceWithDestinationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportCatalog", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportCatalogRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        public ExportCatalogRequest() {
        }
        
        public ExportCatalogRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            this.Agency = Agency;
            this.Partner = Partner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportCatalogResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportCatalogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportCatalogResult;
        
        public ExportCatalogResponse() {
        }
        
        public ExportCatalogResponse(string ExportCatalogResult) {
            this.ExportCatalogResult = ExportCatalogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportRoulette", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportRouletteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        public ExportRouletteRequest() {
        }
        
        public ExportRouletteRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            this.Agency = Agency;
            this.Partner = Partner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportRouletteResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportRouletteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportRouletteResult;
        
        public ExportRouletteResponse() {
        }
        
        public ExportRouletteResponse(string ExportRouletteResult) {
            this.ExportRouletteResult = ExportRouletteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportAvailability", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportAvailabilityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        public ExportAvailabilityRequest() {
        }
        
        public ExportAvailabilityRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            this.Agency = Agency;
            this.Partner = Partner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportAvailabilityResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportAvailabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportAvailabilityResult;
        
        public ExportAvailabilityResponse() {
        }
        
        public ExportAvailabilityResponse(string ExportAvailabilityResult) {
            this.ExportAvailabilityResult = ExportAvailabilityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportFare", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportFareRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        public ExportFareRequest() {
        }
        
        public ExportFareRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportFareResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportFareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportFareResult;
        
        public ExportFareResponse() {
        }
        
        public ExportFareResponse(string ExportFareResult) {
            this.ExportFareResult = ExportFareResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportShipsAndCategories", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportShipsAndCategoriesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        public ExportShipsAndCategoriesRequest() {
        }
        
        public ExportShipsAndCategoriesRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            this.Agency = Agency;
            this.Partner = Partner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportShipsAndCategoriesResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportShipsAndCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportShipsAndCategoriesResult;
        
        public ExportShipsAndCategoriesResponse() {
        }
        
        public ExportShipsAndCategoriesResponse(string ExportShipsAndCategoriesResult) {
            this.ExportShipsAndCategoriesResult = ExportShipsAndCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPorts", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPortsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        public ExportPortsRequest() {
        }
        
        public ExportPortsRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            this.Agency = Agency;
            this.Partner = Partner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportPortsResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportPortsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportPortsResult;
        
        public ExportPortsResponse() {
        }
        
        public ExportPortsResponse(string ExportPortsResult) {
            this.ExportPortsResult = ExportPortsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportItineraryAndSteps", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportItineraryAndStepsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        public ExportItineraryAndStepsRequest() {
        }
        
        public ExportItineraryAndStepsRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportItineraryAndStepsResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportItineraryAndStepsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportItineraryAndStepsResult;
        
        public ExportItineraryAndStepsResponse() {
        }
        
        public ExportItineraryAndStepsResponse(string ExportItineraryAndStepsResult) {
            this.ExportItineraryAndStepsResult = ExportItineraryAndStepsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportExcursions", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportExcursionsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Agency Agency;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation")]
        public Costa.CostaSoap.Partner Partner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string destinationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=1)]
        public string cruiseCode;
        
        public ExportExcursionsRequest() {
        }
        
        public ExportExcursionsRequest(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, string cruiseCode) {
            this.Agency = Agency;
            this.Partner = Partner;
            this.destinationCode = destinationCode;
            this.cruiseCode = cruiseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportExcursionsResponse", WrapperNamespace="http://schemas.costacrociere.com/WebAffiliation", IsWrapped=true)]
    public partial class ExportExcursionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.costacrociere.com/WebAffiliation", Order=0)]
        public string ExportExcursionsResult;
        
        public ExportExcursionsResponse() {
        }
        
        public ExportExcursionsResponse(string ExportExcursionsResult) {
            this.ExportExcursionsResult = ExportExcursionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExportSoapChannel : Costa.CostaSoap.ExportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportSoapClient : System.ServiceModel.ClientBase<Costa.CostaSoap.ExportSoap>, Costa.CostaSoap.ExportSoap {
        
        public ExportSoapClient() {
        }
        
        public ExportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportDestinationResponse Costa.CostaSoap.ExportSoap.ExportDestination(Costa.CostaSoap.ExportDestinationRequest request) {
            return base.Channel.ExportDestination(request);
        }
        
        public string ExportDestination(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode) {
            Costa.CostaSoap.ExportDestinationRequest inValue = new Costa.CostaSoap.ExportDestinationRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            Costa.CostaSoap.ExportDestinationResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportDestination(inValue);
            return retVal.ExportDestinationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportPriceResponse Costa.CostaSoap.ExportSoap.ExportPrice(Costa.CostaSoap.ExportPriceRequest request) {
            return base.Channel.ExportPrice(request);
        }
        
        public string ExportPrice(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            Costa.CostaSoap.ExportPriceRequest inValue = new Costa.CostaSoap.ExportPriceRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            Costa.CostaSoap.ExportPriceResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportPrice(inValue);
            return retVal.ExportPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportPriceWithPaxBreakdownResponse Costa.CostaSoap.ExportSoap.ExportPriceWithPaxBreakdown(Costa.CostaSoap.ExportPriceWithPaxBreakdownRequest request) {
            return base.Channel.ExportPriceWithPaxBreakdown(request);
        }
        
        public string ExportPriceWithPaxBreakdown(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.ExportPriceType expPriceType, Costa.CostaSoap.MaxOccupancy maxOccupancy) {
            Costa.CostaSoap.ExportPriceWithPaxBreakdownRequest inValue = new Costa.CostaSoap.ExportPriceWithPaxBreakdownRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            inValue.expPriceType = expPriceType;
            inValue.maxOccupancy = maxOccupancy;
            Costa.CostaSoap.ExportPriceWithPaxBreakdownResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportPriceWithPaxBreakdown(inValue);
            return retVal.ExportPriceWithPaxBreakdownResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportPriceDetailedResponse Costa.CostaSoap.ExportSoap.ExportPriceDetailed(Costa.CostaSoap.ExportPriceDetailedRequest request) {
            return base.Channel.ExportPriceDetailed(request);
        }
        
        public string ExportPriceDetailed(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.ExportPriceType expPriceType, Costa.CostaSoap.MaxOccupancy maxOccupancy) {
            Costa.CostaSoap.ExportPriceDetailedRequest inValue = new Costa.CostaSoap.ExportPriceDetailedRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            inValue.expPriceType = expPriceType;
            inValue.maxOccupancy = maxOccupancy;
            Costa.CostaSoap.ExportPriceDetailedResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportPriceDetailed(inValue);
            return retVal.ExportPriceDetailedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportGroupPriceWithPaxBreakdownResponse Costa.CostaSoap.ExportSoap.ExportGroupPriceWithPaxBreakdown(Costa.CostaSoap.ExportGroupPriceWithPaxBreakdownRequest request) {
            return base.Channel.ExportGroupPriceWithPaxBreakdown(request);
        }
        
        public string ExportGroupPriceWithPaxBreakdown(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.MaxOccupancy maxOccupancy) {
            Costa.CostaSoap.ExportGroupPriceWithPaxBreakdownRequest inValue = new Costa.CostaSoap.ExportGroupPriceWithPaxBreakdownRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            inValue.maxOccupancy = maxOccupancy;
            Costa.CostaSoap.ExportGroupPriceWithPaxBreakdownResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportGroupPriceWithPaxBreakdown(inValue);
            return retVal.ExportGroupPriceWithPaxBreakdownResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportTravelAgentPriceWithPaxBreakdownResponse Costa.CostaSoap.ExportSoap.ExportTravelAgentPriceWithPaxBreakdown(Costa.CostaSoap.ExportTravelAgentPriceWithPaxBreakdownRequest request) {
            return base.Channel.ExportTravelAgentPriceWithPaxBreakdown(request);
        }
        
        public string ExportTravelAgentPriceWithPaxBreakdown(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.MaxOccupancy maxOccupancy) {
            Costa.CostaSoap.ExportTravelAgentPriceWithPaxBreakdownRequest inValue = new Costa.CostaSoap.ExportTravelAgentPriceWithPaxBreakdownRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            inValue.maxOccupancy = maxOccupancy;
            Costa.CostaSoap.ExportTravelAgentPriceWithPaxBreakdownResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportTravelAgentPriceWithPaxBreakdown(inValue);
            return retVal.ExportTravelAgentPriceWithPaxBreakdownResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportPriceWithDestinationResponse Costa.CostaSoap.ExportSoap.ExportPriceWithDestination(Costa.CostaSoap.ExportPriceWithDestinationRequest request) {
            return base.Channel.ExportPriceWithDestination(request);
        }
        
        public string ExportPriceWithDestination(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, Costa.CostaSoap.ExportPriceType expPriceType) {
            Costa.CostaSoap.ExportPriceWithDestinationRequest inValue = new Costa.CostaSoap.ExportPriceWithDestinationRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            inValue.expPriceType = expPriceType;
            Costa.CostaSoap.ExportPriceWithDestinationResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportPriceWithDestination(inValue);
            return retVal.ExportPriceWithDestinationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportCatalogResponse Costa.CostaSoap.ExportSoap.ExportCatalog(Costa.CostaSoap.ExportCatalogRequest request) {
            return base.Channel.ExportCatalog(request);
        }
        
        public string ExportCatalog(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            Costa.CostaSoap.ExportCatalogRequest inValue = new Costa.CostaSoap.ExportCatalogRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            Costa.CostaSoap.ExportCatalogResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportCatalog(inValue);
            return retVal.ExportCatalogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportRouletteResponse Costa.CostaSoap.ExportSoap.ExportRoulette(Costa.CostaSoap.ExportRouletteRequest request) {
            return base.Channel.ExportRoulette(request);
        }
        
        public string ExportRoulette(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            Costa.CostaSoap.ExportRouletteRequest inValue = new Costa.CostaSoap.ExportRouletteRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            Costa.CostaSoap.ExportRouletteResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportRoulette(inValue);
            return retVal.ExportRouletteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportAvailabilityResponse Costa.CostaSoap.ExportSoap.ExportAvailability(Costa.CostaSoap.ExportAvailabilityRequest request) {
            return base.Channel.ExportAvailability(request);
        }
        
        public string ExportAvailability(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            Costa.CostaSoap.ExportAvailabilityRequest inValue = new Costa.CostaSoap.ExportAvailabilityRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            Costa.CostaSoap.ExportAvailabilityResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportAvailability(inValue);
            return retVal.ExportAvailabilityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportFareResponse Costa.CostaSoap.ExportSoap.ExportFare(Costa.CostaSoap.ExportFareRequest request) {
            return base.Channel.ExportFare(request);
        }
        
        public string ExportFare(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode) {
            Costa.CostaSoap.ExportFareRequest inValue = new Costa.CostaSoap.ExportFareRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            Costa.CostaSoap.ExportFareResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportFare(inValue);
            return retVal.ExportFareResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportShipsAndCategoriesResponse Costa.CostaSoap.ExportSoap.ExportShipsAndCategories(Costa.CostaSoap.ExportShipsAndCategoriesRequest request) {
            return base.Channel.ExportShipsAndCategories(request);
        }
        
        public string ExportShipsAndCategories(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            Costa.CostaSoap.ExportShipsAndCategoriesRequest inValue = new Costa.CostaSoap.ExportShipsAndCategoriesRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            Costa.CostaSoap.ExportShipsAndCategoriesResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportShipsAndCategories(inValue);
            return retVal.ExportShipsAndCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportPortsResponse Costa.CostaSoap.ExportSoap.ExportPorts(Costa.CostaSoap.ExportPortsRequest request) {
            return base.Channel.ExportPorts(request);
        }
        
        public string ExportPorts(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner) {
            Costa.CostaSoap.ExportPortsRequest inValue = new Costa.CostaSoap.ExportPortsRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            Costa.CostaSoap.ExportPortsResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportPorts(inValue);
            return retVal.ExportPortsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportItineraryAndStepsResponse Costa.CostaSoap.ExportSoap.ExportItineraryAndSteps(Costa.CostaSoap.ExportItineraryAndStepsRequest request) {
            return base.Channel.ExportItineraryAndSteps(request);
        }
        
        public string ExportItineraryAndSteps(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode) {
            Costa.CostaSoap.ExportItineraryAndStepsRequest inValue = new Costa.CostaSoap.ExportItineraryAndStepsRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            Costa.CostaSoap.ExportItineraryAndStepsResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportItineraryAndSteps(inValue);
            return retVal.ExportItineraryAndStepsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Costa.CostaSoap.ExportExcursionsResponse Costa.CostaSoap.ExportSoap.ExportExcursions(Costa.CostaSoap.ExportExcursionsRequest request) {
            return base.Channel.ExportExcursions(request);
        }
        
        public string ExportExcursions(Costa.CostaSoap.Agency Agency, Costa.CostaSoap.Partner Partner, string destinationCode, string cruiseCode) {
            Costa.CostaSoap.ExportExcursionsRequest inValue = new Costa.CostaSoap.ExportExcursionsRequest();
            inValue.Agency = Agency;
            inValue.Partner = Partner;
            inValue.destinationCode = destinationCode;
            inValue.cruiseCode = cruiseCode;
            Costa.CostaSoap.ExportExcursionsResponse retVal = ((Costa.CostaSoap.ExportSoap)(this)).ExportExcursions(inValue);
            return retVal.ExportExcursionsResult;
        }
    }
}
